FROM node:18-slim

WORKDIR /app

COPY package.json .
COPY next-env.d.ts .
COPY tsconfig.json .

RUN npm install

COPY . .
RUN rm -rf node_modules
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"] 