version: '3.8'

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/arxio
      - REDIS_URL=redis://redis:6379
      - WORKER_URL=http://worker:8000
    depends_on:
      - postgres
      - redis
      - worker

  worker:
    build:
      context: ./apps/worker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ZAP_API_URL=http://zap:8080/JSON
      - POSTGRES_CONNECTION=postgresql://postgres:postgres@postgres:5432/arxio
    depends_on:
      - redis
      - postgres
      - zap

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=arxio
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    ports:
      - "8080:8080"
    volumes:
      - zap_data:/zap/wrk

volumes:
  postgres_data:
  redis_data:
  zap_data: 